import crypto from "crypto";

/**
 * Modern Iyzico Client
 * NO DEPENDENCIES - Works everywhere (Vercel, Lambda, Edge, Node.js)
 * Fixed "Cannot find module" issues forever.
 */

interface IyzicoConfig {
  apiKey: string;
  secretKey: string;
  uri: string;
}

export class IyzicoClient {
  private config: IyzicoConfig;

  constructor(config: IyzicoConfig) {
    this.config = config;
  }

  private generateRandomString(): string {
    return Math.random().toString(36).substring(2, 15);
  }

  /**
   * Iyzico Signature Algorithm
   * Hash value generated by secretKey + apiKey + randomString + pkiString
   */
  private generateSignature(randomString: string, pkiString: string): string {
    const data = this.config.secretKey + this.config.apiKey + randomString + pkiString;
    return crypto.createHash("sha1").update(data).digest("base64");
  }

  /**
   * Iyzico PKI String Builder
   * Matches official Iyzico Node SDK logic exactly.
   */
  private toPKIString(request: any): string {
    const buildPKI = (obj: any): string => {
      if (Array.isArray(obj)) {
        let str = "[";
        for (let i = 0; i < obj.length; i++) {
          str += buildPKI(obj[i]) + (i < obj.length - 1 ? "," : "");
        }
        return str + "]";
      } else if (obj !== null && typeof obj === "object") {
        let str = "[";
        const keys = Object.keys(obj).sort();
        let first = true;
        for (const key of keys) {
          const value = obj[key];
          if (value !== undefined && value !== null) {
            if (!first) str += ",";
            str += key + "=" + buildPKI(value);
            first = false;
          }
        }
        return str + "]";
      } else {
        return obj.toString();
      }
    };
    return buildPKI(request);
  }

  private async request(path: string, request: any): Promise<any> {
    const randomString = this.generateRandomString();
    const pkiString = this.toPKIString(request);
    const signature = this.generateSignature(randomString, pkiString);

    const headers = {
      "Accept": "application/json",
      "Content-Type": "application/json",
      "Authorization": `IYZWS ${this.config.apiKey}:${signature}`,
      "x-iyzi-rnd": randomString,
    };

    try {
      const response = await fetch(this.config.uri + path, {
        method: "POST",
        headers,
        body: JSON.stringify(request),
      });

      const result = await response.json();
      
      if (result.status === "failure") {
        console.error("Iyzico Error:", result.errorMessage, "Code:", result.errorCode);
      }
      
      return result;
    } catch (error) {
      console.error("Iyzico Request Failed:", error);
      return { status: "failure", errorMessage: "Bağlantı hatası oluştu." };
    }
  }

  public checkoutFormInitialize = {
    create: async (request: any) => {
      return this.request("/payment/iyzipay/checkoutform/initialize/auth/ecom", request);
    }
  };

  public checkoutForm = {
    retrieve: async (request: any) => {
      return this.request("/payment/iyzipay/checkoutform/auth/ecom/detail", request);
    }
  };
}
